### ISSUE TITLE
Casino Heist Control

### ISSUE THREAD

**Issue by Garcia1386** [haekkzer/2Take1Script#1]
Casino Heist Control - Manual Mode,  doenst work.

**Comment by haekkzer** [comment]
I just tested it on a fresh acc.
every heist wont be startable if you dont do the first mission by yourself. the spy casino out or something.

on my other acc where i have it already done, it works like a charm.
if it doesnt work and u already did the mission too, try the "Quick start" followed by the "Reset Heist" and try the manual again.

or be more clear what exactly is not working please.
ty

**Comment by Garcia1386** [comment]
my acc is not fresh, and i did all heists alote of times without mods. and if i use luna and menyoo asi. and works like a charm.

**Comment by haekkzer** [comment]
just to be sure, ur pressing the feature to apply the value? just switchting with num 4 / 6 doesnt do it.
is it a specific entry that does not work?
please be more specific.

**Comment by Garcia1386** [comment]
when i choose the vault target, i got always money, and when i choose the tactic, just dont choose(stay empty), and i dont have skull to play on hard. the second and thirth board appear all white. sorry my bad english bro. can you add hard option on heists?
i tried on others acc (steam and epicgames) and i got same problem.

**Comment by haekkzer** [comment]
Just to be sure, do this:
1. do the "Quick start"
2. "Reset Heist"
itll should look like this now:
[https://gyazo.com/833590ce1f232faca33f7e2c23a86dcd]
Now go to manual mode:
there is one entry that is missing on your end / public version of the script, this one:
[https://gyazo.com/833590ce1f232faca33f7e2c23a86dcd]
there you can select "Hard".
BUT, if this value is not the same as the above Setting, you wont get the max payout. thats the reason why i "hide" it by default.
ill "enable" it in the next version. i guess thats the point / problem your having?
cuz everything else works fine:
[https://gyazo.com/7cd0e0373401abcdf93e50838bcb8ada]
[https://gyazo.com/03ab112b5e6e5b3e81986da21f0765af]

**Comment by Garcia1386** [comment]
thanks, works now :)
