### ISSUE TITLE
Electocute player does not work.

### ISSUE THREAD

**Issue by Joel636** [haekkzer/2Take1Script#4]
**Describe the bug**
I have not even once managed to get "Electrocute player" to work, other than on myself. I'm standing literally right next to the player, I hear the tazer go off, and I see the little "bullet" hit, yet nothing. Nothing happens to the player. 
I suspected this might have something to do with some protection, net event or script event, but after disabling all of them and trying, I now know that that is not the case. I can't for the life of me figure out WHY it isn't working, as I have, as previously mentioned, disabled damn near everything. 

**To Reproduce**
Honestly, I don't know how to reproduce this other than just use the "Electrocute player" feature. 
It's simply not functional for me, yet somehow it is functional for you.

**Expected behavior**
I expected the player to get stunned, ragdoll and fall to the ground.

**Screenshots / Logs**
N/A

**Additional context**
I'm submitting this because I don't know if you are working on finding whatever the cause of the bug is, since it's obviously working fine for you.

**Comment by Joel636** [comment]
**Also tried** 
Using a brand new profile, with no protections or options enabled. Still did not work.

**Comment by haekkzer** [comment]
Sorry for late reply, i will look at it if a got time, thanks.
