### ISSUE TITLE
Crash player option crashes yourself

### ISSUE THREAD

**Issue by gtheman3812** [haekkzer/2Take1Script#5]
**Describe the bug**
When using crash player option, the user is crashed.
**To Reproduce**
1. Go to 'malicious
2. Click on 'crash player

**Expected behavior**
Menu freezes and game stops
**Screenshots / Logs**
`%appdata%\PopstarDevs\2Take1Menu\2Take1Menu.log`
Post the latest error message from this file. / Upload this file.
It will help me find out whats wrong.

**Additional context**

**Comment by Joel636** [comment]
Seconded, happens to me too!

**Comment by haekkzer** [comment]
Since its a weak / old crash with instability, i decided to remove it.
